services:
  - type: web
    name: splitly
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: MONGO_URL
        sync: false
      - key: ROOT_URL
        value: https://splitly-ryao.onrender.com
      - key: PORT
        value: 3000
