services:
  - type: web
    name: splitly
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: MONGO_URL
        fromDatabase:
          name: splitly-db
          property: connectionString
      - key: ROOT_URL
        value: https://splitly-ryao.onrender.com
      - key: PORT
        value: 3000

databases:
  - name: splitly-db
    databaseName: splitly
    user: splitly
    plan: free
